services:
  - type: web
    name: brandion-api
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
